# Generated by Django 3.0 on 2019-12-16 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frapp', '0002_person'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnknownPerson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unknownBase64', models.TextField()),
            ],
        ),
    ]
