# Generated by Django 3.0 on 2019-12-24 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frapp', '0003_unknownperson'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='isExisting',
            field=models.BooleanField(default=False),
        ),
    ]
